# See http://travis-ci.org/encukou/gillcup

language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
    - sudo apt-get install python3-numpy python-pip
    - pip install pytest hypothesis coala-bears
    - pip install -e.
script:
    - python -m pytest -v
    - coala-ci
